# Generated by Django 4.2.6 on 2023-10-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classschedule',
            old_name='fk_nstructor',
            new_name='fk_instructor',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='fk_intructor',
            new_name='fk_intsructor',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='fk_intructor',
            new_name='fk_instructor',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='fk_quizQAndAID',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='maxScore',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='time',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='userScore',
        ),
        migrations.AddField(
            model_name='content',
            name='content_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='quizes',
            name='fk_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmain.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='quizes',
            name='quiz_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='fk_syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.syllabus', verbose_name='Syllabus'),
        ),
    ]
