# Generated by Django 4.2.6 on 2023-10-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmain', '0003_delete_quizqanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profilePicture',
            field=models.ImageField(blank=True, default=1, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profilePicture',
            field=models.ImageField(blank=True, default=1, null=True, upload_to='images/'),
        ),
    ]
